---
image: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/govcms-ci-buildx

services:
  - name: gitlab-registry-production.govcms.amazee.io/govcms/govcms-ci/dind:latest
    command: ["--tls=false"]
    
stages:
  - validate
  - build
  - test

# ---
# Common workflow rules.
# ---
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"
      variables:
        DEPLOY_TAG: "edge"
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        DEPLOY_TAG: "latest"
    - if: $CI_COMMIT_REF_NAME =~ /^release\//
      variables:
        DEPLOY_TAG: "beta"

    ## Testing
    - if: $CI_COMMIT_REF_NAME == "feature/multiarch-apple-silicon" ## Remove after testing.
      variables:
        DEPLOY_TAG: "edge"

    ## Release tags.
    - if: $CI_COMMIT_TAG != null
      variables:
        DEPLOY_TAG: $CI_COMMIT_TAG

    - when: always # Run the pipeline in other cases

.before_script_common: &before_script_common |-
  if [ -z "$DEPLOY_TAG" ]; then echo "DEPLOY_TAG must be set for an actionable build."; exit 1; fi
  cp .env.default .env
  sed -i -e "s/^GOVCMS_RELEASE_TAG.*/GOVCMS_RELEASE_TAG=$DEPLOY_TAG/" .env
  cat .env

# ---
# Alias definitions.
# ---
.variables: &variables
  DOCKER_HOST: tcp://localhost:2375
  BUILDKIT_INLINE_CACHE: '1'
  DOCKER_DRIVER: overlay2

.before_script_build: &before_script_build
  before_script:
    - *before_script_common
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    - export $(grep -v '^#' .env | xargs)
    - docker network prune -f && docker network inspect amazeeio-network >/dev/null || docker network create amazeeio-network
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - ahoy build y
    - docker image list

.test: &test
  variables:
    << : *vars
  before_script:
    - *before_script_build
  script:
    - docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m

validate:containers:
  stage: validate
  script:
    - docker-compose config -q

build:containers:
  stage: build
  before_script:
    - *before_script_build
  needs:
    - validate:containers

test:module_scanning:
  << : *test
  stage: test
  script:
    - ahoy -v install
    - /govcms/vendor/bin/govcms-module_verify
  needs:
    - build:containers
  artifacts:
    paths:
      - $CSV_LOCATION
  only:
    - schedules
