version: '3.0'

x-environment:
  &default-environment
    LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
    X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
    CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

services:

  cli:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms7
      args:
        GOVCMS_PROJECT_VERSION: ${GOVCMS_PROJECT_VERSION:-7.x-3.x}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
        SITE_AUDIT_VERSION: ${SITE_AUDIT_VERSION:-7.x-3.x}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/test:${GOVCMS_RELEASE_TAG:-latest}
    depends_on:
      - cli
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

  nginx:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/nginx-drupal:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}
      LAGOON_LOCALDEV_URL: ${LOCALDEV_URL_NGINX:-http://govcms-lagoon-nginx.docker.amazee.io}
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.4}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/php:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

  mariadb:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.mariadb-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/mariadb-drupal:${GOVCMS_RELEASE_TAG:-latest}
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`

  redis:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.redis
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/redis:${GOVCMS_RELEASE_TAG:-latest}

  solr:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.solr
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/solr:${GOVCMS_RELEASE_TAG:-latest}
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`

  varnish:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.varnish-drupal
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/varnish-drupal:${GOVCMS_RELEASE_TAG:-latest}
    environment:
      LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
      VARNISH_BYPASS: "true"
    networks:
      - amazeeio-network
      - default

  chrome:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.chrome
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test

networks:
  amazeeio-network:
    external: true
  default:
    external: false
